name: buy_and_earn
description: "A new Flutter project."
publish_to: "none"

version: 1.2.8+17

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^2.5.1
  pinput: ^5.0.0
  dio: ^5.5.0+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  path_provider: ^2.1.3
  upgrader: ^10.3.0
  encrypt: ^5.0.3
  crypto: ^3.0.3
  internet_connection_checker_plus: ^2.5.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  firebase_messaging: ^15.0.3
  flutter_local_notifications: ^17.2.1+2
  googleapis_auth: ^1.6.0
  firebase_core: ^3.2.0
  cached_network_image: ^3.4.0
  permission_handler: ^11.3.1
  # contacts_service: ^0.6.3
  webview_flutter: ^4.8.0
  staggered_grid_view_flutter:
  flutter_contacts: ^1.1.9+2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/Service Icons/
    - assets/images/welcome-images/
  fonts:
    - family: Jakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          style: italic
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 900
