// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_JAOiXghKQG48UubfBIlSyWX272BnQuI',
    appId: '1:18786037372:web:c925bd3a2f846128df23f9',
    messagingSenderId: '18786037372',
    projectId: 'buy-n-earn',
    authDomain: 'buy-n-earn.firebaseapp.com',
    databaseURL: 'https://buy-n-earn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buy-n-earn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZBSZpRL_g4BEZhPWj60W65GO9R543Kxo',
    appId: '1:18786037372:android:4a11d16216c68fdbdf23f9',
    messagingSenderId: '18786037372',
    projectId: 'buy-n-earn',
    databaseURL: 'https://buy-n-earn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'buy-n-earn.appspot.com',
  );

}